version: '2'
services:
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=cog
      - POSTGRES_PASSWORD=cog
  cog:
    build:
      context: .
      dockerfile: Dockerfile.ci
    volumes:
      - .:/cog
    depends_on:
      - postgres
    environment:
      - COG_MQTT_HOST=0.0.0.0
      - DATABASE_URL=ecto://cog:cog@postgres:5432/cog
      - SLACK_API_TOKEN=${SLACK_API_TOKEN}
      - SLACK_USER_API_TOKEN=${SLACK_USER_API_TOKEN}
      - HIPCHAT_USER_API_TOKEN=${HIPCHAT_USER_API_TOKEN}
      - HIPCHAT_USER_JID=${HIPCHAT_USER_JID}
      - HIPCHAT_USER_PASSWORD=${HIPCHAT_USER_PASSWORD}
      - HIPCHAT_USER_NICKNAME=${HIPCHAT_USER_NICKNAME}
      - HIPCHAT_ROOMS=${HIPCHAT_ROOMS}
      - HIPCHAT_API_TOKEN=${HIPCHAT_API_TOKEN}
      - HIPCHAT_JABBER_ID=${HIPCHAT_JABBER_ID}
      - HIPCHAT_JABBER_PASSWORD=${HIPCHAT_JABBER_PASSWORD}
      - HIPCHAT_NICKNAME=${HIPCHAT_NICKNAME}
      - TEST_SLACK=${TEST_SLACK}
      - TEST_HIPCHAT=${TEST_HIPCHAT}
