FROM elixir:1.3-slim

# Greenbar-only compilation dependencies
RUN apt-get update && \
    apt-get -yqq install \
      build-essential git-core libexpat1-dev && \
    rm -rf /var/lib/apt/lists/*
#   apt-get -yqq install g++ gcc libstdc++ && \
#   rm -rf /var/lib/apt/lists/*

WORKDIR /code

COPY mix.exs mix.lock /code/
COPY config/ /code/config/

RUN mix do local.hex --force, local.rebar --force, deps.get
RUN MIX_ENV=test mix deps.compile

COPY . /code/

RUN MIX_ENV=test mix compile
