FROM elixir:1.3-slim

LABEL maintainer "Dave Long <me@davejlong.com>"

ENV MIX_ENV dev

# Create directories and upload cog source
WORKDIR /cog

RUN apt-get update && \
    apt-get -yqq install build-essential git libexpat1-dev && \
    rm -rf /var/lib/apt/lists/* && \
    mix do local.hex --force, local.rebar --force

COPY mix.exs mix.lock /cog/
COPY config/ /cog/config/

RUN mix do deps.get --no-archives-check, deps.compile

COPY . /cog

RUN mix compile --no-deps-check --no-archives-check

# This should be in place in the build environment already
COPY cogctl-for-docker-build /usr/local/bin/cogctl

VOLUME ["/cog"]
EXPOSE 4000 4001 4002
CMD ["/cog/scripts/docker-start"]
