FROM operable/elixir:1.3.1-r4

# Greenbar-only compilation dependencies
RUN apk -U add expat-dev gcc g++ libstdc++

COPY mix.exs mix.lock /code/
COPY config/ /code/config/
WORKDIR /code
RUN mix deps.get
RUN MIX_ENV=test mix deps.compile

COPY . /code
RUN MIX_ENV=test mix compile
