#!/bin/bash -x

set -eo pipefail

export ALLOW_WARNINGS=true
export PATH="${PATH}:$(dirname $0)"

[[ -z "${DATABASE_URL}" ]] && echo "Unable to parse DATABASE_URL" && exit 1

read proto user pass host port db <<<$(echo ${DATABASE_URL} | sed -e 's|^\(.*://\)\(.*\)\:\(.*\)\@\(.*\)\:\(.*\)\/\(.*\)|\1 \2 \3 \4 \5 \6|g')

echo "Waiting for Postgres to become available..."
wait-for-it.sh -s -t 0 -h "${host}" -p "${port}" && true

echo "Apply database migrations..."
mix ecto.migrate --no-deps-check

if [[ -n "$COG_BOOTSTRAP_USERNAME" && -n "$COG_BOOTSTRAP_PASSWORD" ]]; then
  echo "Generating a cogctl profile..."
  cogctl profile create default http://localhost:4000 "${COG_BOOTSTRAP_USERNAME}" "${COG_BOOTSTRAP_PASSWORD}"
fi

echo "Launching Cog server..."
elixir --no-halt --name cog@127.0.0.1 -S mix phoenix.server --no-compile --no-deps-check
