#!/bin/sh -x

set -e

# install mix
mix local.hex --force
mix local.rebar --force
mix hex.info

# build cog
cd /home/operable/cog
mix clean
mix deps.get
mix deps.compile
mix compile

# build cogctl
cd /home/operable/cogctl
git clone https://github.com/operable/cogctl .
git checkout v0.12.0
mix deps.get
mix deps.compile
mix escript
